name: ocm-llm-app
region: "nyc1"
domains:
  - domain: "vanguardchangesolutions.com"
  - domain: "www.vanguardchangesolutions.com"
services:
  - name: web
    github:
      repo: "rkjvx8/OCM-LLM2"
      branch: "master"
      deploy_on_push: false
    dockerfile_path: "Dockerfile"
    run_command: "python web.py"
    http_port: 5000
    instance_size_slug: "basic-xxs"
    envs:
      - key: "OPENAI_API_KEY"
        scope: "RUN_TIME"
      - key: "PORT"
        value: "5000"
        scope: "RUN_TIME"
